project:
  type: website

website:
  title: "Baltimore Public Art Inventory"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: map.qmd
        text: Map
      - href: data.qmd
        text: Data


format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

